/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <main.h>

extern volatile uint16_t dma2_status;
extern volatile uint32_t adc_data[3];


int main(void){

	clock_max_config();
	adc_init();
	adc_start();

	while(1){
		if(dma2_status) {
		// Reset flag
		dma2_status = 0;
		}



	}
}



